site_name: Bluz Docs
site_favicon: http://bluz.io/static/img/bluz_only_logo.png
pages:
- Home: index.md
- Tutorials:
  - 'Getting Started': tutorials/getting_started.md
- Reference:
  - 'Cloud Functions': reference/cloud.md
  - 'Input/Output': reference/io.md
  - 'Serial': reference/serial.md
  - 'System': reference/system.md
- Hardware:
  - 'Bluz DK': hardware/dk.md
  - 'CR2032 Battery Shield': hardware/battery.md
- Troubleshooting: troubleshoot.md
extra_css:
    - css/styles.css
