site_name: Bluz Docs
site_favicon: http://bluz.io/static/img/bluz_only_logo.png
pages:
- Home: index.md
- Tutorials:
  - 'Getting Started': tutorials/getting_started.md
  - 'Operating States': tutorials/states.md
  - 'Talking Serial': tutorials/serial.md
- Reference:
  - 'Bluetooth LE': reference/ble.md
  - 'Cloud Functions': reference/cloud.md
  - 'Input/Output': reference/io.md
  - 'Interrupts': reference/interrupts.md
  - 'Serial': reference/serial.md
  - 'SPI': reference/spi.md
  - 'System': reference/system.md
  - 'RGB': reference/rgb.md
- Hardware:
  - 'Bluz DK': hardware/dk.md
  - 'CR2032 Battery Shield': hardware/battery.md
- Troubleshooting:
  - "SOS Codes": troubleshooting/sos.md
extra_css:
    - css/styles.css
